<#
.SYNOPSIS
    RackStack - All-in-one Windows Server setup utility (Monolithic Build).

.DESCRIPTION
    This is the MONOLITHIC BUILD -- all 63 modules combined into a single file.
    Generated by sync-to-monolithic.ps1 from the modular source in Modules/.
    The .exe is compiled from this file via ps2exe.

    For development, use RackStack.ps1 (the modular loader) instead.

    Features include:
    - Configure Host or Virtual Machine networking (IP, DNS, VLAN)
    - Configure Switch Embedded Teaming (SET) for Hyper-V hosts
    - Configure iSCSI NICs with proper isolation
    - Set hostname with validation
    - Join Active Directory domain
    - Set timezone (US timezones)
    - Install Windows Updates with timeout protection
    - Enable Remote Desktop with firewall rules
    - Configure Windows Firewall profiles
    - License Windows Server (volume, AVMA, manual)
    - Create local administrator accounts with password complexity
    - Disable built-in Administrator account with self-cleanup
    - Test network connectivity
    - Configure power plans
    - Generate batch configuration templates

.AUTHOR
    7h3 4b1d3r

.VERSION
    1.5.1

.LAST UPDATED
    02/23/2026

.CHANGELOG v1.4.1
    BUG FIXES:
    - FIXED: Undo stack parameter ordering now uses hashtable splatting instead of positional array
    - FIXED: Bare Exit replaced with [Environment]::Exit(0) for ps2exe EXE compatibility
    - FIXED: Per-adapter internet detection on PS 5.x uses ping.exe -S for source-bound ping
    - FIXED: NIC disable for identification now warns if adapter carries default route (management NIC)

.CHANGELOG v1.4.0
    NEW FEATURES:
    - ADDED: Server Role Templates (Module 60) - 10 built-in templates (DC, FS, WEB, DHCP, DNS, PRINT, WSUS, NPS, HV, RDS) with custom templates via defaults.json
    - ADDED: AD DS Promotion (Module 61) - New Forest, Additional DC, RODC wizards with prerequisite checks
    - ADDED: Hyper-V Replica Management (Module 62) - Enable replica server, replication wizard, status dashboard, test/planned failover, reverse replication
    - ADDED: 2 new batch steps (14: Server Role Template, 15: DC Promotion), total steps 20 -> 22
    - ADDED: System Config menu option [3] Promote to Domain Controller, renumbered [3]-[6] -> [4]-[7]
    - ADDED: Storage & Clustering menu option [6] Hyper-V Replica Management
    - ADDED: Tools menu [8] now launches full template installer (was simple role list)
    - ADDED: Add-CommandHistory function for recording menu navigation
    BUG FIXES:
    - FIXED: Undo stack corrupted when single item (array slice [0..-1] returned item instead of empty)
    - FIXED: Install-WindowsFeatureWithTimeout checking non-existent $result.Success instead of $result.ExitCode
    - FIXED: Get-WindowsVersionInfo error path returning inconsistent keys
    - FIXED: Duplicate Defender process exclusion (vmwp.exe / Vmwp.exe case duplicate)
    - FIXED: Command history never recording
    - FIXED: $localadminaccountname missing $script: prefix in batch mode
    - FIXED: Test-Connection -Source failing on PowerShell < 6 (Server 2012 R2)

.CHANGELOG v1.3.0
    NEW FEATURES:
    - ADDED: Storage Backend Generalization - iSCSI, Fibre Channel, S2D, SMB3, NVMe-oF, Local backends
    - ADDED: Module 59-StorageBackends with unified abstraction layer and per-backend management menus
    - ADDED: FC support (HBAs, WWPNs, MPIO), S2D (pool/virtual disk management), SMB3, NVMe-oF
    - ADDED: Initialize-MPIOForBackend dispatches to correct bus type
    - ADDED: Storage & SAN Management menu adapts to active backend
    - ADDED: Backend-aware batch mode with StorageBackendType and ConfigureSharedStorage keys
    - ADDED: Settings menu option [8] to change storage backend
    - 60 modules (was 59), backward compatible with all existing configs

.CHANGELOG v1.2.0
    NEW FEATURES:
    - ADDED: Custom SET vNICs with Add-CustomVNIC (preset or custom names, VLAN, inline IP config)
    - ADDED: iSCSI A/B Side Ping Check via Test-iSCSICabling (auto-detect adapter-to-switch mapping)
    - ADDED: iSCSI auto-config integration (ping check before manual A/B selection)
    - ADDED: Batch mode CustomVNICs key, total batch steps 19 -> 20
    - ADDED: Export-BatchConfigFromState detects vNICs on SET
    - ADDED: iSCSI menu option [3] Test iSCSI Cabling
    - RENAMED: Host Network [2] from "Add Backup NIC to SET" to "Add Virtual NIC to SET"
    - RENAMED: FileServer.KaseyaFolder to FileServer.AgentFolder (backward-compatible)

.CHANGELOG v1.1.0
    NEW FEATURES:
    - ADDED: Dynamic Defender paths auto-generated from selected host drive
    - ADDED: 5 new HOST batch steps (Host Storage, SET, iSCSI, MPIO, Defender Exclusions)
    - ADDED: Batch Config from State - detect live config and generate batch_config.json
    - ADDED: Executable Favorites - selecting a favorite runs the action directly
    - ADDED: Configuration Drift Detection in Operations menu

.CHANGELOG v1.0.18
    MAINTENANCE:
    - Minor refinements and cleanup

.CHANGELOG v1.0.17
    IMPROVEMENTS:
    - ADDED: 123 new tests across 8 sections (94-101), total now 1187
    - UPDATED: Reorganized local-only files into local/ directory

.CHANGELOG v1.0.16
    IMPROVEMENTS:
    - ADDED: Branding assets (banner, social preview, icon SVG/PNGs, favicon)
    - UPDATED: Self-hosted CI runner for pushes, GitHub-hosted for PRs

.CHANGELOG v1.0.15
    IMPROVEMENTS:
    - UPDATED: Rewrote defaults.example.json with comprehensive beginner-friendly comments
    - ADDED: New server rack icon

.CHANGELOG v1.0.14
    IMPROVEMENTS:
    - RENAMED: AbiderCloud to FileServer across all modules, config keys, functions, tests, docs
    - FIXED: Exit cleanup targeting for EXE, monolithic, and config files

.CHANGELOG v1.0.13
    NEW FEATURES:
    - ADDED: Generic VM Templates (DC, FS, WEB) with CustomVMTemplates in defaults.json
    - ADDED: Configurable VM Naming with token-based patterns via VMNaming config
    - ADDED: Linux VHD cloud-init preparation guide
    - ADDED: Dynamic agent naming via AgentInstaller.ToolName

.CHANGELOG v1.0.12
    NEW FEATURES:
    - ADDED: AutoUpdate flag in defaults.json for automatic update-on-startup

.CHANGELOG v1.0.11
    BUG FIXES:
    - FIXED: Console auto-sizing via Win32 API (maximizes window, expands buffer)

.CHANGELOG v1.0.10
    IMPROVEMENTS:
    - ADDED: 4 new test sections (90-93), ~50 new tests, total 1040+

.CHANGELOG v1.0.9
    IMPROVEMENTS:
    - REFACTORED: New-DeployedVM split into 8 focused helpers
    - ADDED: Remote Pre-flight Checks (Test-RemoteReadiness, 5-step connectivity check)

.CHANGELOG v1.0.8
    NEW FEATURES:
    - ADDED: Configurable Agent Installer (MSP-agnostic framework via defaults.json)
    - ADDED: Configurable SAN target mappings, Defender paths, storage paths, temp directory
    - ADDED: Batch mode pre-flight validation (Test-BatchConfig)

.CHANGELOG v1.0.7
    IMPROVEMENTS:
    - FIXED: EXE monolithic build-from-scratch appends Assert-Elevation entry point
    - FIXED: EXE self-update uses [Environment]::Exit(0) for ps2exe compatibility
    - ADDED: EXE icon via -IconFile in release.ps1
    - ADDED: Error handling audit, inline docs, troubleshooting guide, operations runbooks

.CHANGELOG v1.0.6
    IMPROVEMENTS:
    - ADDED: GitHub Actions CI (test suite, PSScriptAnalyzer, monolithic sync)
    - ADDED: Build from scratch when monolithic doesn't exist (CI mode)
    - ADDED: CI-safe tests skip gracefully when defaults.json absent

.CHANGELOG v1.0.5
    NEW FEATURES:
    - ADDED: Configurable VM Templates via CustomVMTemplates in defaults.json
    - ADDED: Custom VM Defaults (vCPU, RAM, memory type, disk size, disk type)
    - ADDED: Partial overrides, re-import safe, disk conversion

.CHANGELOG v1.0.4
    BUG FIXES:
    - FIXED: $script:ModuleRoot detection in compiled EXE mode (ps2exe fallback)

.CHANGELOG v1.0.3
    IMPROVEMENTS:
    - ADDED: Automatic update check on startup with main menu banner notification
    - ADDED: [U] shortcut on main menu to install updates directly
    - ADDED: Custom exe icon (RackStack.ico)
    - FIXED: Auto-update not detecting new versions (was manual-only, now checks on startup)
    - FIXED: Secret scan false positives in test code (use variables instead of literals)
    - FIXED: PSAvoidUsingWMICmdlet exclusion for PS 2.0 bootstrap script

.CHANGELOG v1.0.2
    COMPATIBILITY:
    - ADDED: Install-Prerequisites.ps1 bootstrap for WMF 5.1 (Server 2008 R2 SP1, 2012, 2012 R2)
    - ADDED: Server 2012 (non-R2) and Server 2008 R2 SP1 OS detection
    - UPDATED: OS support range now 2008 R2 SP1 through 2025

.CHANGELOG v1.0.1
    FIXES & IMPROVEMENTS:
    - ADDED: First-run setup wizard (generates defaults.json interactively on first launch)
    - ADDED: Auto-update from GitHub releases (exe and ps1 self-update)
    - ADDED: Windows Server 2012 R2 compatibility (SET/StorageReplica/Defender guards, TLS 1.2)
    - FIXED: Changelog version numbering (pre-release versions renumbered to 0.x.y)
    - FIXED: Monolithic filename defaults to "RackStack" instead of deriving from ToolFullName
    - FIXED: PSScriptAnalyzer settings cover test scripts
    - UPDATED: README with exe+json download instructions

.CHANGELOG v1.0.0
    INITIAL OPEN SOURCE RELEASE:
    - ADDED: defaults.example.json template for environment configuration
    - ADDED: docs/FileServer-Setup.md guide for setting up file server
    - ADDED: Modular architecture (63 modules) with sync-to-monolithic build
    - ADDED: 905 automated tests, PSScriptAnalyzer validation, release checks
    - ADDED: Batch mode for unattended server builds via JSON config
    - UPDATED: All paths use $PSScriptRoot-relative (no hardcoded user paths)
    - UPDATED: Semantic versioning starting at v1.0.0

.CHANGELOG v0.11.0 (internal v2.9.0)
    NEW FEATURES:
    - ADDED: Pre-flight validation (Show-PreFlightCheck) - network, domain, storage readiness checks
    - ADDED: Menu status indicators - live [OK]/[--] status for configure server menu items
    - ADDED: Role templates (Show-RoleTemplates) - auto-configure common server roles (File, Print, PACS, etc.)
    - ADDED: JSON audit logging (Show-AuditLog) - structured change tracking with export
    - ADDED: Network Diagnostics submenu - ping, port test, traceroute, subnet sweep, DNS lookup, connections, ARP
    - ADDED: Operations Menu - Remote PS Session, Remote Health Check, Remote Service Manager
    - ADDED: FileServer integration (replaced Nextcloud) - ISOs, VHDs, Kaseya agents via REST API
    - ADDED: Quick Setup Wizard (Show-QuickSetupWizard) - guided initial server configuration
    - ADDED: Server Readiness report (Show-ServerReadiness) - comprehensive deployment readiness score
    - ADDED: Performance Dashboard (Show-PerformanceDashboard) - real-time CPU/RAM/disk/network monitoring
    - ADDED: Health dashboard on main menu - hostname, OS, uptime, CPU%, RAM%, C: free space
    - ADDED: Write-MenuItem helper for theme-aware menu rendering
    - ADDED: Get-CachedValue TTL caching system
    - ADDED: Test-WindowsServer function with client OS guards on server-only features
    - ADDED: Centralized constants ($script:PowerPlanGUID, $script:WindowsLicensingAppId)
    - ADDED: Kaseya post-install verification with service polling
    - ADDED: Domain join pre-flight DNS resolution check
    - ADDED: IP config rollback on failure
    - ADDED: Disk space validation before cloud downloads
    - ADDED: SET creation polling loop for vNIC appearance
    - ADDED: MPIO failure logging via Add-SessionChange
    IMPROVEMENTS:
    - UPDATED: Navigation labels with descriptive [B] Back to {parent}
    - UPDATED: RDP NLA uses proper try/catch with warning
    - UPDATED: iSCSI adapter validation with partial failure tracking
    - UPDATED: Kaseya pagination, sorting, dedup, hostname flow
    - UPDATED: DNS menu refactored to dynamic preset list
    - UPDATED: Console resize uses Win32 P/Invoke for ps2exe compatibility
    - UPDATED: defaults.json ships with custom values + KMS keys
    - UPDATED: All regions flattened to top-level (non-nested)
    - UPDATED: 755 automated tests (63 sections), PSScriptAnalyzer 0 errors

.CHANGELOG v0.10.0 (internal v2.6.0)
    NEW FEATURES - SET SMART AUTO-DETECTION:
    - ADDED: Test-AdapterInternetConnectivity - identifies which NICs have internet
    - ADDED: Auto-detect mode in SET configuration - selects NICs with internet automatically
    - ADDED: Automatic identification of iSCSI candidate adapters (NICs without internet)
    - ADDED: Option to configure iSCSI immediately after SET creation
    NEW FEATURES - iSCSI SMART AUTO-CONFIGURATION:
    - ADDED: Get-HostNumberFromHostname - extracts host number from hostname (e.g., HV2 = 2)
    - ADDED: Get-iSCSIAutoIP - calculates iSCSI IPs based on host number (172.16.1.{host}x)
    - ADDED: Test-SANTargetConnectivity - pings SAN targets to verify connectivity
    - ADDED: iSCSI auto-configure mode - detects host#, calculates IPs, configures A/B sides
    - ADDED: Get-SANTargetsForHost - returns correct SAN targets per host (cycling A0/B1, A1/B0, etc.)
    NEW FEATURES - iSCSI & SAN MANAGEMENT MENU:
    - ADDED: New submenu for complete iSCSI/SAN management
    - ADDED: Disable-NICForIdentification - temporarily disable NICs to identify on switch
    - ADDED: Connect-iSCSITargets - connect to SAN with multipath support
    - ADDED: Initialize-MPIOForISCSI - configure MPIO for iSCSI (Round Robin)
    - ADDED: Show-iSCSIStatus - display sessions, targets, MPIO status, disk mappings
    - ADDED: Disconnect-iSCSITargets - gracefully disconnect iSCSI sessions
    NEW FEATURES - UTILITIES:
    - ADDED: Compare-ConfigurationProfiles - diff two JSON profiles with color output
    - ADDED: Test-ScriptUpdate - check for script updates (configurable URL)
    - ADDED: Test-ComputerNameInAD - pre-check if computer name exists in AD
    - ADDED: Test-IPAddressInUse - check if IP is already in use (ping + DNS + ARP)
    - ADDED: Invoke-RemoteProfileApply - apply profiles to remote servers via WinRM
    - ADDED: Credential Manager - store/retrieve domain and remote server credentials
    MENU CHANGES:
    - UPDATED: Host Network menu [4] now opens iSCSI & SAN Management submenu
    - UPDATED: Settings menu now has 9 options with Utilities section
    - ADDED: [5] Compare Configuration Profiles in Settings
    - ADDED: [6] Check for Script Updates in Settings
    - ADDED: [7] Manage Stored Credentials in Settings
    - ADDED: [8] Remote Profile Application in Settings

.CHANGELOG v0.9.0 (internal v2.5.0)
    HELP & DOCUMENTATION:
    - UPDATED: Configure Server menu items renumbered (MPIO [5], Clustering [6] added)
    - ADDED: VHD & ISO Management section to Help
    - ADDED: Deployment options documentation (VHD/blank disk/batch queue)
    - ADDED: Two new tips for VHD deploy and VM queue
    CONFIGURATION PROFILES:
    - ADDED: InstallMPIO flag in Save-ConfigurationProfile
    - ADDED: InstallFailoverClustering flag in Save-ConfigurationProfile
    - ADDED: MPIO install step in Import-ConfigurationProfile (step 9/13)
    - ADDED: Failover Clustering install step in Import-ConfigurationProfile (step 10/13)
    - ADDED: Local Admin creation step in Import-ConfigurationProfile (step 11/13)
    - ADDED: Disable Built-in Admin step in Import-ConfigurationProfile (step 12/13)
    - ADDED: Preview lines for MPIO/Clustering in profile apply preview
    BATCH CONFIGURATION:
    - ADDED: InstallMPIO field in batch template
    - ADDED: InstallFailoverClustering field in batch template
    - ADDED: CreateLocalAdmin field in batch template
    - ADDED: LocalAdminName field in batch template
    - ADDED: DisableBuiltInAdmin field in batch template
    - UPDATED: Start-BatchMode now has 14 steps (was 10)
    EXPORT:
    - ADDED: MPIO status section in Export-ServerConfiguration
    - ADDED: Failover Clustering status section in Export-ServerConfiguration
    - ADDED: Cluster name and node list in export when clustered
    SETTINGS MENU:
    - ADDED: View Changelog option in Settings menu
    MAINTENANCE:
    - ADDED: Automatic transcript cleanup (removes logs older than 30 days)
    UI/UX:
    - FIXED: All menu boxes standardized to 72-char inner width
    - FIXED: Host IP Config and VM Network menu PadRight(58→60) for 72-char alignment
    - FIXED: Firewall color logic (Green = Domain:Off Private:Off Public:On)

.CHANGELOG v0.8.0 (internal v2.4.0)
    NEW FEATURES - SYSPREPPED VHD DEPLOYMENT:
    - ADDED: Download sysprepped VHDs from Google Drive (Server 2019/2022/2025)
    - ADDED: VHD caching - checks if already downloaded, offers to reuse or re-download
    - ADDED: Copy cached dynamic VHD per VM, convert to fixed, rename for VM
    - ADDED: Offline VHD customization before first boot (mount, inject registry settings)
    - ADDED: Pre-boot configuration: computer name, RDP, timezone, power plan, PS Remoting
    - ADDED: SetupComplete.cmd first-boot script for firewall rules and PS Remoting
    - ADDED: VHD Management menu with download status for all OS versions
    - ADDED: Sysprep VHD creation guide (step-by-step instructions)
    NEW FEATURES - ISO DOWNLOAD:
    - ADDED: Download Server ISOs from Google Drive (2019/2022/2025)
    - ADDED: Host ISOs stored in D:\ISOs, Cluster ISOs in C:\ClusterStorage\Volume1\ISOs
    - ADDED: ISO download status and management menu
    NEW FEATURES - HOST STORAGE SETUP:
    - ADDED: D: drive validation - checks if D: is a data drive vs optical/DVD
    - ADDED: Automatic DVD/CD drive remount from D: to free letter
    - ADDED: Disk size check (rejects drives < 20GB)
    - ADDED: Opens Disk Management if no D: data drive found
    - ADDED: Creates D:\Virtual Machines, D:\ISOs, D:\Virtual Machines\_BaseImages
    - ADDED: Sets Hyper-V default VM and VHD paths to D:\Virtual Machines
    HELPER FUNCTIONS:
    - ADDED: Get-GoogleDriveFile - reusable Google Drive download with progress
    - ADDED: Test-OpticalDrive - detects CD/DVD/ISO mounted drives
    - ADDED: Get-NextAvailableDriveLetter - finds free drive letters
    - ADDED: Move-OpticalDriveFromD - remounts optical drives off D:
    - ADDED: Initialize-HostStorage - full D: drive setup workflow
    - ADDED: Get-SyspreppedVHD - download/cache sysprepped VHDs
    - ADDED: Copy-VHDForVM - copy and convert dynamic VHD to fixed
    - ADDED: Set-OfflineVHDConfiguration - offline registry injection
    - ADDED: Show-OfflineCustomizationPrompt - pre-boot config wizard
    NEW FEATURES - VM DEPLOYMENT:
    - ADDED: Full VM Deployment system for Standalone hosts and Failover Clusters
    - ADDED: Connection modes - Local host, Remote host, or Failover Cluster
    - ADDED: Automatic site number detection from hostname (e.g., 123456-HV1 -> 123456)
    - ADDED: Standard VM templates: FS, PS, PACS, EVP, APP, COMM, REPT
    - ADDED: OS Type support (Windows/Linux) with automatic Secure Boot template selection
    - ADDED: Multi-disk template support (C + D drives defined per template)
    - ADDED: Custom VM deployment with full configuration options
    - ADDED: VM name collision detection (checks Hyper-V and DNS)
    - ADDED: Automatic next-available name suggestion (e.g., FS1 exists -> suggest FS2)
    - ADDED: Multiple disk configuration with Fixed (default) or Dynamic types
    - ADDED: Multiple NIC configuration with VLAN support
    - ADDED: Virtual switch detection and selection
    - ADDED: Generation 2 VMs with Secure Boot by default
    - ADDED: Guest Services integration configuration
    - ADDED: Time Sync auto-disabled for Domain Controllers
    - ADDED: Cluster Shared Volume (CSV) path detection for clusters
    - ADDED: View existing VMs on connected host/cluster
    - ADDED: VM-specific subdirectories for organization
    - ADDED: Automatic start/stop action configuration
    - ADDED: Production checkpoints enabled, automatic checkpoints disabled
    - ADDED: VM notes with creation timestamp
    - ADDED: Improved dynamic memory settings (sensible min/startup/max)
    HELPER FUNCTIONS:
    - ADDED: Get-SiteNumberFromHostname - extract site from naming convention
    - ADDED: Test-HyperVConnection - verify Hyper-V connectivity
    - ADDED: Test-ClusterConnection - verify cluster connectivity
    - ADDED: Find-LocalCluster - detect if running on cluster node
    - ADDED: Test-VMNameExists - check for VM name collisions
    - ADDED: Test-VMNameInDNS - check DNS for existing records
    - ADDED: Get-NextAvailableVMName - suggest available names
    - ADDED: Get-AvailableVirtualSwitches - list switches on host
    - ADDED: Get-AvailableVMStoragePaths - get default storage locations
    CONFIGURATION SYSTEM:
    - ADDED: VM Configuration builder with editable settings
    - ADDED: CPU configuration (1-64 vCPUs)
    - ADDED: Memory configuration (Static or Dynamic, 1-1024 GB)
    - ADDED: Disk management (add, edit, delete disks)
    - ADDED: NIC management (add, edit, delete, VLAN assignment)
    - ADDED: Configuration summary with full review before creation
    STORAGE MANAGER IMPROVEMENTS (v2.3 fixes):
    - IMPROVED: Get-DiskHealthStatus now uses multiple correlation methods
    - IMPROVED: Select-Partition now filters Recovery partitions and uses GPT GUIDs
    - IMPROVED: Select-Disk now identifies and warns about OS disk
    - IMPROVED: Clear-DiskData excludes OS disk from selection for safety
    - ADDED: Allocation unit size option in Format Volume (4K-64K)
    - ADDED: OS disk protection with extra confirmation warnings
    - ADDED: Better error messages with troubleshooting tips

.CHANGELOG v0.7.0 (internal v2.3.0)
    NEW FEATURES - STORAGE MANAGER:
    - ADDED: Full Storage Manager with 14 disk management options
    - ADDED: View All Disks - shows disk status, health, size, partition style, bus type
    - ADDED: View All Volumes - shows drive letters, labels, file systems, space usage
    - ADDED: View Disk Partitions - detailed partition information per disk
    - ADDED: Initialize Disk - initialize RAW disks as GPT or MBR
    - ADDED: Set Disk Online/Offline - bring disks online or take them offline
    - ADDED: Clear Disk - wipe all partitions and data (with safety confirmations)
    - ADDED: Create Partition - create new partitions with size and drive letter options
    - ADDED: Delete Partition - remove partitions (with safety warnings for system partitions)
    - ADDED: Format Volume - format with NTFS, ReFS, or exFAT, quick or full format
    - ADDED: Extend Volume - extend partitions into unallocated space
    - ADDED: Shrink Volume - shrink partitions to create free space
    - ADDED: Change Drive Letter - assign, change, or remove drive letters
    - ADDED: Change Volume Label - rename volume labels
    HELPER FUNCTIONS:
    - ADDED: Format-ByteSize - human-readable byte formatting (KB/MB/GB/TB)
    - ADDED: Get-DiskHealthStatus - retrieve physical disk health
    - ADDED: Select-Disk - disk selection with filtering options
    - ADDED: Select-Partition - partition selection helper
    SAFETY FEATURES:
    - Multiple confirmation prompts for destructive operations
    - Type-to-confirm (YES/DELETE/FORMAT) for dangerous operations
    - Warnings for system/boot partitions
    - Color-coded health and usage indicators

.CHANGELOG v0.6.0 (internal v2.2.0)
    NEW FEATURES:
    - ADDED: Restructured main menu with "Configure Server" and "Deploy VMs"
    - ADDED: System Health Check - CPU, RAM, disk, network, services status (now option 1)
    - ADDED: Enable PowerShell Remoting - secure WinRM configuration with Kerberos auth
    - ADDED: Install Kaseya Agent - downloads installer from Google Drive by site number
    - ADDED: Save Configuration Profile - export settings as JSON for cloning to other servers
    - ADDED: Load Configuration Profile - apply saved settings to new servers
    - ADDED: Disable IPv6 option in VM Network configuration menu
    - ADDED: Undo functionality for network, system, and security changes
    - ADDED: Network adapter rename option in Host Network menu
    - ADDED: Transcript logging to C:\Temp\ with timestamped filenames
    - ADDED: Write-PressEnter helper function for consistent UX
    - ADDED: Smart caching for Configure Server menu status display
    SECURITY:
    - IMPROVED: Password handling now uses ZeroFreeBSTR for secure memory cleanup
    - ADDED: Clear-SecureMemory function for proper plaintext password disposal
    - IMPROVED: try/finally blocks ensure passwords are always cleaned from memory
    BUG FIXES:
    - FIXED: Duplicate $script:ScriptStartTime assignment removed
    - FIXED: Batch config template now uses dynamic version number
    - FIXED: Added error handling to Format-LinkSpeed function
    - FIXED: Password attempt counter now shows correct remaining attempts
    - FIXED: Removed duplicate Undo-LastChange function
    - FIXED: Consolidated Add-UndoAction/Add-UndoOperation into single function
    CODE QUALITY:
    - RENAMED: Is-HyperVInstalled to Test-HyperVInstalled (PowerShell convention)
    - RENAMED: Is-RebootPending to Test-RebootPending (PowerShell convention)
    - RENAMED: Is-ServerActivated to Test-ServerActivated (PowerShell convention)
    - RENAMED: Check-PasswordComplexity to Test-PasswordComplexity
    - RENAMED: Check-WindowsVersion to Get-WindowsVersionInfo
    - RENAMED: Configure-VM-IP to Set-VMIPAddress
    - RENAMED: Configure-VM-DNS to Set-VMDNSAddress
    - RENAMED: Configure-VLAN to Set-AdapterVLAN
    - RENAMED: Configure-SET to New-SwitchEmbeddedTeam
    - RENAMED: Configure-iSCSI to Set-iSCSIConfiguration
    - RENAMED: Display-AdaptersTable to Show-AdaptersTable
    - RENAMED: Ensure-Elevation to Assert-Elevation
    - RENAMED: Log-MessageToFile to Write-LogMessage
    - REFACTORED: DNS preset configuration to use helper function
    - IMPROVED: Session tracking for Enable-RDP, local admin, firewall, hostname, domain join
    - IMPROVED: Consistent Write-PressEnter usage throughout


.CHANGELOG v0.5.1 (internal v2.1.1)
    RESTORED FEATURES:
    - RESTORED: Full Register-ServerLicense functionality from v1.7.0
    - RESTORED: KMS client setup keys for Server 2008 through 2025
    - RESTORED: AVMA keys for Server 2012 R2 through 2025 (including Essentials and Azure editions)
    - RESTORED: Guided workflow asking Host vs VM licensing path
    - RESTORED: Datacenter host detection for AVMA eligibility
    - RESTORED: Retry logic with attempt counter for manual key entry
    BUG FIXES:
    - FIXED: Duplicate $script:ScriptStartTime assignment removed
    - FIXED: Batch config template now uses dynamic version number
    - FIXED: Added error handling to Format-LinkSpeed function
    IMPROVEMENTS:
    - ADDED: Session tracking for Enable-RDP function
    - ADDED: Session tracking for local admin account creation
    - ADDED: Session tracking for firewall configuration
    - ADDED: Session tracking for hostname changes
    - ADDED: Session tracking for domain join
    - ADDED: Session tracking for disabling built-in admin
    - ADDED: Navigation command support in Select-Physical-Adapters
    - ADDED: Navigation command support in Select-iSCSI-Adapters
    - ADDED: Navigation command support throughout licensing menus
    - IMPROVED: Shows available editions when license key not found
    - IMPROVED: Confirmation prompt before applying AVMA keys

.CHANGELOG v0.5.0 (internal v2.1.0)
    NEW FEATURES:
    - ADDED: NIC link speed display in adapter tables (10Mbps to 10Gbps+)
    - ADDED: Refresh option ('R') in adapter selection menus
    - ADDED: Test Network Connectivity function (pings gateway, DNS, internet)
    - ADDED: Power Plan configuration (High Performance recommended)
    - ADDED: Batch config template generator (creates JSON with all options)
    - ADDED: Color themes (Default, Dark, Light, Matrix, Ocean)
    - ADDED: Help system (type 'help' at main menu)
    - ADDED: Undo framework for reverting changes
    - ADDED: Settings menu (Theme/Help/Undo)
    - ADDED: DNS presets expanded (Custom, Google, Cloudflare, OpenDNS, Quad9)
    - MOVED: Test Connectivity to option 2 for quick access
    - IMPROVED: Status column widened for "Disconnected"
    - IMPROVED: Better error messages with examples

.CHANGELOG v0.4.0 (internal v2.0.0)
    NEW FEATURES:
    - ADDED: Disable IPv6 option in Host Network menu
    - ADDED: Install Hyper-V as main menu option
    - ADDED: Backup NIC creation option for SET configurations
    - ADDED: Universal "back", "cancel", "exit" command handling
    - ADDED: DNS presets (Custom Domain DNS via defaults.json)
    - ADDED: Progress indicators for long operations
    - ADDED: Session summary on exit with runtime
    - ADDED: Export configuration to file
    - ADDED: Batch mode support (JSON config file)
    BUG FIXES:
    - FIXED: Timezone function name conflict (renamed to Set-ServerTimeZone)
    - FIXED: Hyper-V detection for Windows Client vs Server
    - FIXED: Reboot detection in session summary
    - FIXED: Main Menu navigation from sub-menus
    - FIXED: Windows version detection (Windows 10/11 with version)
    - IMPROVED: VLAN error handling with adapter name detection
    - IMPROVED: Network status refresh after configuration

.CHANGELOG v0.3.0 (internal v1.9.0)
    IMPROVEMENTS:
    - FIXED: Clear-Host added before all adapter selection tables
    - FIXED: All adapter selections now show both UP and DOWN adapters
    - IMPROVED: Consistent screen clearing throughout
    - IMPROVED: Color-coded adapter status
    - KEPT: Hyper-V check before SET configuration

.CHANGELOG v0.2.0 (internal v1.8.0)
    BUG FIXES:
    - FIXED: iSCSI confirmation logic (changed -or to -and)
    - FIXED: Typo 'col1umnWidths' breaking parameter passing
    - FIXED: Typo 'R ead-Host' with extra space
    - FIXED: Wrong parameter '-ForegroundColor' should be '-color'
    - FIXED: Invalid 'Break 2' syntax - changed to 'Exit'
    - FIXED: $null comparison order
    - FIXED: VLAN menu calling wrong function
    - FIXED: $MyInvocation.MyCommand.Path scope issue
    - FIXED: Domain join credential re-prompting
    - FIXED: Duplicate timezone prompts
    NEW FEATURES:
    - ADDED: Input validation for hostnames, IPs, VLANs
    - ADDED: Windows Update timeout protection (5 min)
    - ADDED: VLAN configuration for Hyper-V adapters
    - ADDED: Network connectivity checks
    - ADDED: "back" command in menus
    IMPROVEMENTS:
    - IMPROVED: Global variable initialization
    - IMPROVED: Error messages with hints
    - IMPROVED: Password minimum 14 characters

.CHANGELOG v0.1.0 (internal v1.7.0)
    - ADDED: iSCSI NIC configuration with isolation
    - ADDED: Separate Host vs VM network menus
    - IMPROVED: Menu organization

.EXAMPLE
    .\RackStack.ps1

.EXAMPLE
    # Batch mode - create batch_config.json in same folder, then run script

.NOTES
    - Requires Windows Server 2008 R2 SP1 or later (or Windows 10/11 for testing)
    - Must be run as Administrator
    - Network changes may disconnect remote sessions
    - For batch mode on Hyper-V hosts: Install Hyper-V and build SET via GUI first
#>

#Requires -Version 5.1

# PSScriptAnalyzer suppressions for by-design patterns
[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingWriteHost', '', Justification='Console UI tool requires Write-Host for colored output')]
[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidGlobalVars', '', Justification='Global RebootNeeded flag used for cross-function state')]
[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseShouldProcessForStateChangingFunctions', '', Justification='Interactive tool with built-in confirmations')]
[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingEmptyCatchBlock', '', Justification='Intentional silent error handling for optional features')]
[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseUsingScopeModifierInNewRunspaces', '', Justification='Start-Job uses param() with -ArgumentList pattern')]
[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseSingularNouns', '', Justification='Plural nouns used for clarity when dealing with collections')]
param()

