<#
.SYNOPSIS
    RackStack - Modular Loader (Development)

.DESCRIPTION
    This is the MODULAR LOADER -- it dot-sources all 63 modules from the Modules/
    subfolder and starts RackStack. Use this file for development and testing.

    This is NOT the monolithic build. The monolithic single-file version is:
        RackStack v{version}.ps1  (generated by sync-to-monolithic.ps1)
    The .exe is compiled from the monolithic, not from this loader.

    Environment-specific settings are configured via defaults.json.

.VERSION
    1.8.1

.NOTES
    - Requires Windows Server 2012 R2 or later (or Windows 10/11 for testing)
    - Must be run as Administrator
    - All modules are loaded from the Modules subfolder
    - For production deployment, use the monolithic .ps1 or the compiled .exe
#>

#Requires -Version 5.1

# Get the script's directory
$script:ModuleRoot = $PSScriptRoot

# Verify running as administrator - auto-elevate if not
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host "This script requires administrative privileges. Restarting with elevation..." -ForegroundColor Yellow
    Start-Process powershell -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs
    exit
}

# Define module load order (dependencies first)
$moduleFiles = @(
    "00-Initialization.ps1"
    "01-Console.ps1"
    "02-Logging.ps1"
    "03-InputValidation.ps1"
    "04-Navigation.ps1"
    "05-SystemCheck.ps1"
    "06-NetworkAdapters.ps1"
    "07-IPConfiguration.ps1"
    "08-VLAN.ps1"
    "09-SET.ps1"
    "10-iSCSI.ps1"
    "11-Hostname.ps1"
    "12-DomainJoin.ps1"
    "13-Timezone.ps1"
    "14-WindowsUpdates.ps1"
    "15-RDP.ps1"
    "16-Firewall.ps1"
    "17-DefenderExclusions.ps1"
    "18-FirewallTemplates.ps1"
    "19-NTPConfiguration.ps1"
    "20-DiskCleanup.ps1"
    "21-Licensing.ps1"
    "22-Password.ps1"
    "23-LocalAdmin.ps1"
    "24-DisableAdmin.ps1"
    "25-HyperV.ps1"
    "26-MPIO.ps1"
    "27-FailoverClustering.ps1"
    "28-PerformanceDashboard.ps1"
    "29-EventLogViewer.ps1"
    "30-ServiceManager.ps1"
    "31-BitLocker.ps1"
    "32-Deduplication.ps1"
    "33-StorageReplica.ps1"
    "34-Help.ps1"
    "35-Utilities.ps1"
    "36-BatchConfig.ps1"
    "37-HealthCheck.ps1"
    "38-StorageManager.ps1"
    "39-FileServer.ps1"
    "40-HostStorage.ps1"
    "41-VHDManagement.ps1"
    "42-ISODownload.ps1"
    "43-OfflineVHD.ps1"
    "44-VMDeployment.ps1"
    "45-ConfigExport.ps1"
    "46-SessionSummary.ps1"
    "47-ExitCleanup.ps1"
    "48-MenuDisplay.ps1"
    "49-MenuRunner.ps1"
    "50-EntryPoint.ps1"
    "51-ClusterDashboard.ps1"
    "52-VMCheckpoints.ps1"
    "53-VMExportImport.ps1"
    "54-HTMLReports.ps1"
    "55-QoLFeatures.ps1"
    "56-OperationsMenu.ps1"
    "57-KaseyaInstaller.ps1"
    "58-NetworkDiagnostics.ps1"
    "59-StorageBackends.ps1"
    "60-ServerRoleTemplates.ps1"
    "61-ActiveDirectory.ps1"
    "62-HyperVReplica.ps1"
)

# Load all modules
$modulesPath = Join-Path $script:ModuleRoot "Modules"

Write-Host "Loading configuration tool modules..." -ForegroundColor Cyan

$loadedCount = 0
$errorCount = 0

foreach ($module in $moduleFiles) {
    $modulePath = Join-Path $modulesPath $module

    if (Test-Path $modulePath) {
        try {
            . $modulePath
            $loadedCount++
        }
        catch {
            Write-Host "  ERROR loading $module : $_" -ForegroundColor Red
            $errorCount++
        }
    }
    else {
        Write-Host "  WARNING: Module not found: $module" -ForegroundColor Yellow
        $errorCount++
    }
}

if ($errorCount -gt 0) {
    Write-Host "`nLoaded $loadedCount modules with $errorCount errors." -ForegroundColor Yellow
    Write-Host "Some functionality may be unavailable." -ForegroundColor Yellow
    Read-Host "Press Enter to continue anyway, or Ctrl+C to exit"
}

# Start the tool (calls Assert-Elevation which handles transcript and launches menu)
Assert-Elevation
