# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: TheAbider.RackStack
PackageVersion: 1.98.0
MinimumOSVersion: 10.0.0.0
InstallerType: portable
Commands:
  - RackStack
Scope: user
ElevationRequirement: elevationRequired  # the tool itself needs admin to do anything useful
ReleaseDate: 2026-04-18
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/TheAbider/RackStack/releases/download/v1.98.0/RackStack.exe
    InstallerSha256: 1250F350012DA8656DB1ED1EC4D1555D4A06F44B9CE3C829EB5F2DE18F2C8E9F
ManifestType: installer
ManifestVersion: 1.6.0